import { test, expect } from '@playwright/test';

// Interfaz intuitiva para realizar una denuncia
test('DenunciaAnonima', async ({ page }) => {
  await page.goto('http://localhost/alertatec/');
  await page.getByRole('button', { name: 'IR' }).click();
  await page.getByRole('link', { name: 'Formulario' }).click();
  await page.getByRole('button', { name: 'Comenzar' }).click();
  await page.locator('#anonimo_si').check();
  await page.getByRole('button', { name: 'Siguiente' }).click();
  await page.getByLabel('Persona afectada', { exact: true }).check();
  await page.getByLabel('Alumno').check();
  await page.getByLabel('¿A qué carrera perteneces?').click();
  await page.getByLabel('¿A qué carrera perteneces?').press('CapsLock');
  await page.getByLabel('¿A qué carrera perteneces?').fill('S');
  await page.getByLabel('¿A qué carrera perteneces?').press('CapsLock');
  await page.getByLabel('¿A qué carrera perteneces?').fill('Sistemas');
  await page.getByLabel('¿En qué semestre te').selectOption('7');
  await page.getByRole('button', { name: 'Siguiente' }).click();
  await page.locator('#seccion3 > input').first().check();
  await page.locator('input:nth-child(10)').check();
  await page.locator('input:nth-child(16)').check();
  await page.getByLabel('¿Cuándo ocurrió el incidente?').fill('2024-11-07');
  await page.getByLabel('Dentro de la institución').check();
  await page.getByLabel('Describir el lugar (aula,').click();
  await page.getByLabel('Describir el lugar (aula,').press('CapsLock');
  await page.getByLabel('Describir el lugar (aula,').fill('L');
  await page.getByLabel('Describir el lugar (aula,').press('CapsLock');
  await page.getByLabel('Describir el lugar (aula,').fill('Laboratorio de computo');
  await page.getByLabel('7. Indica el número de').selectOption('1');
  await page.getByRole('radio', { name: 'Alumno' }).check();
  await page.getByLabel('Proporciona el nombre del agresor 1:').click();
  await page.getByLabel('Proporciona el nombre del agresor 1:').press('CapsLock');
  await page.getByLabel('Proporciona el nombre del agresor 1:').fill('A');
  await page.getByLabel('Proporciona el nombre del agresor 1:').press('CapsLock');
  await page.getByLabel('Proporciona el nombre del agresor 1:').fill('Agresor');
  await page.getByLabel('8. Proporciona una descripció').click();
  await page.getByLabel('8. Proporciona una descripció').press('CapsLock');
  await page.getByLabel('8. Proporciona una descripció').fill('D');
  await page.getByLabel('8. Proporciona una descripció').press('CapsLock');
  await page.getByLabel('8. Proporciona una descripció').fill('Descripcion del hecho');
  await page.getByRole('button', { name: 'Siguiente' }).click();
  await page.getByRole('radio', { name: 'No' }).check();
  await page.getByLabel('Indica el número de testigos.').selectOption('1');
  await page.getByRole('radio', { name: 'Alumno' }).check();
  await page.getByLabel('10.2 Proporciona el nombre').click();
  await page.getByLabel('10.2 Proporciona el nombre').press('CapsLock');
  await page.getByLabel('10.2 Proporciona el nombre').fill('T');
  await page.getByLabel('10.2 Proporciona el nombre').press('CapsLock');
  await page.getByLabel('10.2 Proporciona el nombre').fill('Testigo');
  await page.getByRole('button', { name: 'Siguiente' }).click();
  await page.getByLabel('No, prefiero no recibir').check();
  await page.getByRole('radio', { name: 'No', exact: true }).check();
  await page.getByRole('button', { name: 'Enviar denuncia' }).click();
});

test('DenunciaNoAnonima', async ({ page }) => {
  await page.goto('http://localhost/alertatec/');
  await page.getByRole('button', { name: 'IR' }).click();
  await page.getByRole('link', { name: 'Formulario' }).click();
  await page.getByRole('button', { name: 'Comenzar' }).click();
  await page.locator('#anonimo_no').check();
  await page.getByLabel('Nombre completo:').click();
  await page.getByLabel('Nombre completo:').fill('S');
  await page.getByLabel('Nombre completo:').press('CapsLock');
  await page.getByLabel('Nombre completo:').fill('Sebastian ');
  await page.getByLabel('Nombre completo:').press('CapsLock');
  await page.getByLabel('Nombre completo:').fill('Sebastian R');
  await page.getByLabel('Nombre completo:').press('CapsLock');
  await page.getByLabel('Nombre completo:').fill('Sebastian Rodriguez ');
  await page.getByLabel('Nombre completo:').press('CapsLock');
  await page.getByLabel('Nombre completo:').fill('Sebastian Rodriguez C');
  await page.getByLabel('Nombre completo:').press('CapsLock');
  await page.getByLabel('Nombre completo:').fill('Sebastian Rodriguez Cervantes');
  await page.getByLabel('Correo Electrónico (').fill('sebasrdz88@gmail.com');
  await page.getByLabel('Número telefónico (opcional):').fill('8719999999');
  await page.getByRole('button', { name: 'Siguiente' }).click();
  await page.getByLabel('Persona afectada', { exact: true }).check();
  await page.getByLabel('Alumno').check();
  await page.getByLabel('¿A qué carrera perteneces?').click();
  await page.getByLabel('¿A qué carrera perteneces?').press('CapsLock');
  await page.getByLabel('¿A qué carrera perteneces?').fill('S');
  await page.getByLabel('¿A qué carrera perteneces?').press('CapsLock');
  await page.getByLabel('¿A qué carrera perteneces?').fill('Sistemas');
  await page.getByLabel('¿En qué semestre te').selectOption('7');
  await page.getByRole('button', { name: 'Siguiente' }).click();
  await page.locator('#seccion3 > input').first().check();
  await page.locator('input:nth-child(10)').check();
  await page.locator('input:nth-child(16)').check();
  await page.getByLabel('¿Cuándo ocurrió el incidente?').fill('2024-11-07');
  await page.getByLabel('Dentro de la institución').check();
  await page.getByLabel('Describir el lugar (aula,').click();
  await page.getByLabel('Describir el lugar (aula,').press('CapsLock');
  await page.getByLabel('Describir el lugar (aula,').fill('L');
  await page.getByLabel('Describir el lugar (aula,').press('CapsLock');
  await page.getByLabel('Describir el lugar (aula,').fill('Laboratorio de computo');
  await page.getByLabel('7. Indica el número de').selectOption('1');
  await page.getByRole('radio', { name: 'Alumno' }).check();
  await page.getByLabel('Proporciona el nombre del agresor 1:').click();
  await page.getByLabel('Proporciona el nombre del agresor 1:').press('CapsLock');
  await page.getByLabel('Proporciona el nombre del agresor 1:').fill('A');
  await page.getByLabel('Proporciona el nombre del agresor 1:').press('CapsLock');
  await page.getByLabel('Proporciona el nombre del agresor 1:').fill('Agresor');
  await page.getByLabel('8. Proporciona una descripció').click();
  await page.getByLabel('8. Proporciona una descripció').press('CapsLock');
  await page.getByLabel('8. Proporciona una descripció').fill('D');
  await page.getByLabel('8. Proporciona una descripció').press('CapsLock');
  await page.getByLabel('8. Proporciona una descripció').fill('Descripcion del hecho');
  await page.getByRole('button', { name: 'Siguiente' }).click();
  await page.getByRole('radio', { name: 'No' }).check();
  await page.getByLabel('Indica el número de testigos.').selectOption('1');
  await page.getByRole('radio', { name: 'Alumno' }).check();
  await page.getByLabel('10.2 Proporciona el nombre').click();
  await page.getByLabel('10.2 Proporciona el nombre').press('CapsLock');
  await page.getByLabel('10.2 Proporciona el nombre').fill('T');
  await page.getByLabel('10.2 Proporciona el nombre').press('CapsLock');
  await page.getByLabel('10.2 Proporciona el nombre').fill('Testigo');
  await page.getByRole('button', { name: 'Siguiente' }).click();
  await page.getByLabel('No, prefiero no recibir').check();
  await page.getByRole('radio', { name: 'No', exact: true }).check();
  await page.getByRole('button', { name: 'Enviar denuncia' }).click();
});

test('CampoSinLlenar', async ({ page }) => {
await page.goto('http://localhost/alertatec/');
await page.getByRole('button', { name: 'IR' }).click();
await page.getByRole('button', { name: 'Ir a formulario' }).click();
await page.getByRole('button', { name: 'Comenzar' }).click();
page.once('dialog', dialog => {
    console.log(`Dialog message: ${dialog.message()}`);
    dialog.dismiss().catch(() => {});
  });
  await page.locator('#seccion1').getByRole('button', { name: 'Siguiente' }).click();
});


//Anonimato y protección de datos
test('DenunciaAnonimaBD', async ({ page }) => {
  await page.goto('http://localhost/alertatec/');
  await page.getByRole('button', { name: 'IR' }).click();
  await page.getByRole('link', { name: 'Formulario' }).click();
  await page.getByRole('button', { name: 'Comenzar' }).click();
  await page.locator('#anonimo_si').check();
  await page.getByRole('button', { name: 'Siguiente' }).click();
  await page.getByLabel('Persona afectada', { exact: true }).check();
  await page.getByLabel('Alumno').check();
  await page.getByLabel('¿A qué carrera perteneces?').click();
  await page.getByLabel('¿A qué carrera perteneces?').press('CapsLock');
  await page.getByLabel('¿A qué carrera perteneces?').fill('S');
  await page.getByLabel('¿A qué carrera perteneces?').press('CapsLock');
  await page.getByLabel('¿A qué carrera perteneces?').fill('Sistemas');
  await page.getByLabel('¿En qué semestre te').selectOption('7');
  await page.getByRole('button', { name: 'Siguiente' }).click();
  await page.locator('#seccion3 > input').first().check();
  await page.locator('input:nth-child(10)').check();
  await page.locator('input:nth-child(16)').check();
  await page.getByLabel('¿Cuándo ocurrió el incidente?').fill('2024-11-07');
  await page.getByLabel('Dentro de la institución').check();
  await page.getByLabel('Describir el lugar (aula,').click();
  await page.getByLabel('Describir el lugar (aula,').press('CapsLock');
  await page.getByLabel('Describir el lugar (aula,').fill('L');
  await page.getByLabel('Describir el lugar (aula,').press('CapsLock');
  await page.getByLabel('Describir el lugar (aula,').fill('Laboratorio de computo');
  await page.getByLabel('7. Indica el número de').selectOption('1');
  await page.getByRole('radio', { name: 'Alumno' }).check();
  await page.getByLabel('Proporciona el nombre del agresor 1:').click();
  await page.getByLabel('Proporciona el nombre del agresor 1:').press('CapsLock');
  await page.getByLabel('Proporciona el nombre del agresor 1:').fill('A');
  await page.getByLabel('Proporciona el nombre del agresor 1:').press('CapsLock');
  await page.getByLabel('Proporciona el nombre del agresor 1:').fill('Agresor');
  await page.getByLabel('8. Proporciona una descripció').click();
  await page.getByLabel('8. Proporciona una descripció').press('CapsLock');
  await page.getByLabel('8. Proporciona una descripció').fill('D');
  await page.getByLabel('8. Proporciona una descripció').press('CapsLock');
  await page.getByLabel('8. Proporciona una descripció').fill('Descripcion del hecho');
  await page.getByRole('button', { name: 'Siguiente' }).click();
  await page.getByRole('radio', { name: 'No' }).check();
  await page.getByLabel('Indica el número de testigos.').selectOption('1');
  await page.getByRole('radio', { name: 'Alumno' }).check();
  await page.getByLabel('10.2 Proporciona el nombre').click();
  await page.getByLabel('10.2 Proporciona el nombre').press('CapsLock');
  await page.getByLabel('10.2 Proporciona el nombre').fill('T');
  await page.getByLabel('10.2 Proporciona el nombre').press('CapsLock');
  await page.getByLabel('10.2 Proporciona el nombre').fill('Testigo');
  await page.getByRole('button', { name: 'Siguiente' }).click();
  await page.getByLabel('Sí, deseo recibir').check();
  await page.locator('#correoDA').click();
  await page.locator('#correoDA').fill('sebasrdz88');
  await page.locator('#correoDA').press('Alt+6');
  await page.locator('#correoDA').press('Alt+4');
  await page.locator('#correoDA').fill('sebasrdz88@gmail.com');
  await page.getByRole('radio', { name: 'No', exact: true }).check();
  await page.getByRole('button', { name: 'Enviar denuncia' }).click();

  await page.goto('http://localhost/phpmyadmin/index.php?route=/database/structure&db=alertatec');
  await page.getByRole('cell', { name: 'denunciante', exact: true }).getByRole('link').click();
});

//Denuncia con opciones personalizadas
test('DenunciaOpciones', async ({ page }) => {
await page.goto('http://localhost/alertatec/');
  await page.getByRole('button', { name: 'IR' }).click();
  await page.getByRole('link', { name: 'Formulario' }).click();
  await page.getByRole('button', { name: 'Comenzar' }).click();
  await page.locator('#anonimo_si').check();
  await page.getByRole('button', { name: 'Siguiente' }).click();
  await page.getByLabel('Persona afectada', { exact: true }).check();
  await page.getByLabel('Alumno').check();
  await page.getByLabel('¿A qué carrera perteneces?').click();
  await page.getByLabel('¿A qué carrera perteneces?').press('CapsLock');
  await page.getByLabel('¿A qué carrera perteneces?').fill('S');
  await page.getByLabel('¿A qué carrera perteneces?').press('CapsLock');
  await page.getByLabel('¿A qué carrera perteneces?').fill('Sistemas');
  await page.getByLabel('¿En qué semestre te').selectOption('7');
  await page.getByRole('button', { name: 'Siguiente' }).click();

  await page.locator('input:nth-child(19)').first().check();
  await page.locator('input:nth-child(7)').check();
  await page.locator('#seccion3 > input').first().check();
  await page.locator('input:nth-child(19)').first().uncheck();
  await page.getByLabel('¿Cuándo ocurrió el incidente?').fill('2024-11-07');
  await page.getByLabel('Dentro de la institución').check();
  await page.getByLabel('Describir el lugar (aula,').click();
  await page.getByLabel('Describir el lugar (aula,').press('CapsLock');
  await page.getByLabel('Describir el lugar (aula,').fill('L');
  await page.getByLabel('Describir el lugar (aula,').press('CapsLock');
  await page.getByLabel('Describir el lugar (aula,').fill('Laboratorio de computo');
  await page.getByLabel('7. Indica el número de').selectOption('1');
  await page.getByRole('radio', { name: 'Alumno' }).check();
  await page.getByLabel('Proporciona el nombre del agresor 1:').click();
  await page.getByLabel('Proporciona el nombre del agresor 1:').press('CapsLock');
  await page.getByLabel('Proporciona el nombre del agresor 1:').fill('A');
  await page.getByLabel('Proporciona el nombre del agresor 1:').press('CapsLock');
  await page.getByLabel('Proporciona el nombre del agresor 1:').fill('Agresor');
  await page.getByLabel('8. Proporciona una descripció').click();
  await page.getByLabel('8. Proporciona una descripció').press('CapsLock');
  await page.getByLabel('8. Proporciona una descripció').fill('D');
  await page.getByLabel('8. Proporciona una descripció').press('CapsLock');
  await page.getByLabel('8. Proporciona una descripció').fill('Descripcion del hecho');
  await page.getByRole('button', { name: 'Siguiente' }).click();
  await page.getByRole('radio', { name: 'No' }).check();
  await page.getByLabel('Indica el número de testigos.').selectOption('1');
  await page.getByRole('radio', { name: 'Alumno' }).check();
  await page.getByLabel('10.2 Proporciona el nombre').click();
  await page.getByLabel('10.2 Proporciona el nombre').press('CapsLock');
  await page.getByLabel('10.2 Proporciona el nombre').fill('T');
  await page.getByLabel('10.2 Proporciona el nombre').press('CapsLock');
  await page.getByLabel('10.2 Proporciona el nombre').fill('Testigo');
  await page.getByRole('button', { name: 'Siguiente' }).click();
  await page.getByLabel('Sí, deseo recibir').check();
  await page.locator('#correoDA').click();
  await page.locator('#correoDA').fill('sebasrdz88');
  await page.locator('#correoDA').press('Alt+6');
  await page.locator('#correoDA').press('Alt+4');
  await page.locator('#correoDA').fill('sebasrdz88@gmail.com');
  await page.getByRole('radio', { name: 'No', exact: true }).check();
  await page.getByRole('button', { name: 'Enviar denuncia' }).click();
});

//Log In
//ADMINISTRADOR 
test('LoginAdmin', async ({ page }) => {
await page.goto('http://localhost/alertatec/');
await page.getByRole('link').click();
await page.getByLabel('Usuario:').click();
await page.getByLabel('Usuario:').press('CapsLock');
await page.getByLabel('Usuario:').fill('A');
await page.getByLabel('Usuario:').press('CapsLock');
await page.getByLabel('Usuario:').fill('Administrador');
await page.getByLabel('Contraseña:').click();
await page.getByLabel('Contraseña:').fill('adminlag1');
await page.getByRole('button', { name: 'Administrador', exact: true }).click();
await page.getByText('☰').click();
await page.getByRole('button', { name: 'Cerrar sesión' }).click();
await page.goto('http://localhost/alertatec/login.php');
});

test('LoginAdminContraseñaInvalida', async ({ page }) => {
  await page.goto('http://localhost/alertatec/');
  await page.getByRole('link').click();
  await page.getByLabel('Usuario:').click();
  await page.getByLabel('Usuario:').press('CapsLock');
  await page.getByLabel('Usuario:').fill('A');
  await page.getByLabel('Usuario:').press('CapsLock');
  await page.getByLabel('Usuario:').fill('Administrador');
  await page.getByLabel('Contraseña:').click();
  await page.getByLabel('Contraseña:').fill('adminlag');
  await page.getByRole('button', { name: 'Administrador', exact: true }).click();
  });

//Log In
//SUPER-ADMINISTRADOR 
test('LoginSuperAdmin', async ({ page }) => {
  await page.goto('http://localhost/alertatec/');
  await page.getByRole('link').click();
  await page.getByLabel('Usuario:').click();
  await page.getByLabel('Usuario:').press('CapsLock');
  await page.getByLabel('Usuario:').fill('S');
  await page.getByLabel('Usuario:').press('CapsLock');
  await page.getByLabel('Usuario:').fill('Super');
  await page.getByLabel('Usuario:').press('CapsLock');
  await page.getByLabel('Usuario:').fill('SuperA');
  await page.getByLabel('Usuario:').press('CapsLock');
  await page.getByLabel('Usuario:').fill('SuperAdmin');
  await page.getByLabel('Contraseña:').fill('superadmin1');
  await page.getByRole('button', { name: 'SuperAdministrador' }).click();
  await page.getByText('☰').click();
  await page.getByRole('button', { name: 'Cerrar sesión' }).click();
  });

  test('LoginSuperAdminContraseñaInvalida', async ({ page }) => {
  await page.goto('http://localhost/alertatec/');
  await page.getByRole('link').click();
  await page.getByLabel('Usuario:').click();
  await page.getByLabel('Usuario:').press('CapsLock');
  await page.getByLabel('Usuario:').fill('S');
  await page.getByLabel('Usuario:').press('CapsLock');
  await page.getByLabel('Usuario:').fill('Super');
  await page.getByLabel('Usuario:').press('CapsLock');
  await page.getByLabel('Usuario:').fill('SuperA');
  await page.getByLabel('Usuario:').press('CapsLock');
  await page.getByLabel('Usuario:').fill('SuperAdmin');
  await page.getByLabel('Contraseña:').click();
  await page.getByLabel('Contraseña:').fill('contrasena');
  await page.getByRole('button', { name: 'SuperAdministrador' }).click();
  });

